### ISSUE TITLE
More constrained AST

### ISSUE THREAD

**Issue by Armael** [ocaml/opam-file-format#14]
It seems to me (but maybe I'm mistaking?) that the current parser and AST is quite lax, and allows things that would get rejected by opam at a later stage. Would it make sense to somehow expose a bit more structure?

It would be nice to have a more constrained AST, or maybe runtime invariant checks on the current one, that describe more precisely the structure of files that are actually accepted by opam. 
At the moment, to make sense of the AST I can look at all the packages in opam-repository and infer the structure from them, but it feels ad-hoc...

**Comment by dra27** [comment]
What use-case do you have in mind for this? The output of this parser is an AST for the *format* only - `OpamFile` in the `opam-format` package is responsible for converting those to the actual structures, with potential for errors. The modules in `OpamFile` all include functions for reading a particular opam file specification from either a string, channel or filename.

The purpose of the opam-file-format library is to provide an extremely lightweight library for parsing and lexing the format for tools which don't pull the dependencies of opam-format (which are considerable) into their dependency cone.

**Comment by Armael** [comment]
Yes, my bad; I think at that time what I wanted to use was rather what is in `OpamFile`.

**Comment by dra27** [comment]
No problem!
