### ISSUE TITLE
Feature request : json printer

### ISSUE THREAD

**Issue by abate** [ocaml/opam-file-format#15]
I need to modify an opam file. This lib is perfect to write an ad-hoc ml tool to do this job (imagine adding a build step ) . However, instead of writing a tool for each type of modification I want to do it would be nice to have a parser from opam format to json, then using jq for the modification and parse back the result in opam format. ```opam-file-format -tojson <opamfile> | jq .... | opam-file-format -fromjson > <opamfile>```

**Comment by abate** [comment]
I realized that adding yojson will pull a zillion dependencies that have nothing to do with this lib. Closed

**Comment by dra27** [comment]
Indeed, the aim of this library is to have absolutely minimal dependencies - have you come across https://github.com/AltGr/opam-ed, in case that's helpful for what you wanted to do?
