### ISSUE TITLE
No license file?

### ISSUE THREAD

**Issue by TC01** [ocaml/opam-file-format#5]
The opam file says that opam-file-format is under LGPLv2.1 with OCaml exception, and [source code](https://github.com/ocaml/opam-file-format/blob/master/src/opamBaseParser.mly) has headers that refer to a LICENSE file, e.g by saying: "with the special exception on linking described in the file LICENSE".

However... there is no LICENSE file in the repository. Any chance this could be fixed?

**Comment by AltGr** [comment]
Indeed, thanks for pointing it out!
