### ISSUE TITLE
No `.cmxs` installed

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam-file-format#6]
It would be nice to generate `opam-file-format.cmxs` so that the library can be used in `ocamlnat`.

**Comment by dra27** [comment]
@AltGr - there's a jbuild file in Opam's src_ext .. perhaps we should 'upstream' it 🙂

**Comment by dbuenzli** [comment]
Please don't, `opam-file-format` is supposed to have no dependencies.

**Comment by dra27** [comment]
We'd be eliminating a dependency on `make`, which is a nuisance and only adding a build dependency on `jbuilder`, which is not!

**Comment by dra27** [comment]
(Entirely incidentally, jbuilder also contains a jbuild file for opam-file-format)

**Comment by dbuenzli** [comment]
It will be more problematic to bootstrap the eco-system. `make` is anyways needed by `ocaml` so nuisance or not you will need it.

**Comment by dra27** [comment]
How is it more problematic?

**Comment by dbuenzli** [comment]
A lot of packages now rely on `.install` files to install, and we should provide system packagers with a simple bootstrap story for that (recently I had to implement a `Makefile` build system for `cmdliner` because we somehow managed to create a circular dependency for system packagers which you don't see when you install through `opam`). 

More generally I think it is good to promote the `opam` file format as the metadata format for the eco-system and as such it's good if the codec for this unfortunately odd file format simply depends on no more than the ocaml system/and its dependencies itself. This was discussed to death in https://github.com/ocaml/opam/issues/2682 and https://github.com/ocaml/opam/issues/2677.

Besides I understand a lot of people seem to be overly excited by `jbuilder` but to be honest I don't see a good reason to introduce a `jbuilder` dependency here. There are quite a few other tools in the eco-system that might use this package and which don't necessarily need a `jbuilder` (transitive) dependency (e.g. `odig`).

**Comment by avsm** [comment]
I do agree with @dbuenzli here that a jbuilder dependency seems unnecessary at this stage.  Some tools like `depext` and `opam-installer` are just simpler to package if they are standalone as possible. There is an additional maintenance burden (e.g. this issue), but simplifying OS package maintainers lives is generally easier.

It would be really nice to have jbuilder output a portable shell script at some stage that could give us the best of both worlds...
