### ISSUE TITLE
License file has GPL 3 text instead of LGPL 2.1

### ISSUE THREAD

**Issue by mehdid** [ocaml/opam-file-format#8]
The license file says that all files are distributed under GNU LESSER GENERAL PUBLIC LICENSE v2.1
with STATIC LINKING EXCEPTION, but has GPL-3's text below the exception.

**Comment by andyli** [comment]
Indeed... Please clarify which is the right one.

**Comment by maximedenes** [comment]
@gasche @AltGr Can we get a clarification of what is the license of this library? We are about to use it in a coq-related tool, and it will probably have implications on the license of the tool. Thank you.

**Comment by dra27** [comment]
Note that `LICENSE` is unambiguous - it clearly states that it's LGPL 2.1 and the text of LGPL 2.1 is *below* the GPL v3 text. However, it's obviously unnecessary for it to be there at all, see #17!
